### ISSUE TITLE
UPDATE 29.0 PLEASE

### ISSUE THREAD

**Issue by MazerUNKNOW** [Ferrster/Snowrunner-Manual-Gearbox-Mod#21]

**Comment by Manueelite** [comment]
Please Update :-)

**Comment by Snuppers** [comment]
This is an excellent mod. Would love to see it updated so I can keep using it. Makes the game so much better!

**Comment by RixClash** [comment]
Обновите пожалуйста! Нет больше сил нажимать шифт что бы заставить эту чертову коробку переключаться вовремя! Обязуюсь выключить автоматическое обновление!

**Comment by Funky-Punky** [comment]
Hey @Ferrster 
I just wanted to offer my help. From what I can see in the commit history, updating this mod is just a matter of changing a few pointers? I tried to understand the code on my own, but to no success. :( (Maybe because I don't know any c++) 
Nevertheless I am confident, that I could help you with updating the mod. I study computer science, so I know a thing or two about this stuff. If you let me join you and explain the process of updating the mod to me, I could do it myself the next time and create a pr or something.

I don't want to offend you or anything, I just want to save you the hassle of reading a few passive aggressive GitHub messages each month(like this one😇)

**Comment by Ferrster** [comment]
[Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.9). Sorry for the delay(

@Funky-Punky Yes, the process of updating the mod consists of updating pointers to game functions and data. I finally saved some AOBs to find those functions faster. Feel free to dm me in Telegram (@ferrster) if you're interested, and I'll try my best to explain the process:)
